### ISSUE TITLE
Validate with, height of create playground form

### ISSUE THREAD

**Issue by Haseb-ali** [Haseb-ali/DPMS#2]
Need proper validation of width and height of create playground form width and height must be number and only in km validate properly at front

**Comment by Muhammad-Ahmad-Ali069** [comment]
Are you talking about validation at frontend or server side?

**Comment by Haseb-ali** [comment]
Client side only

**Comment by Haseb-ali** [comment]
This is the target form
![68747470733a2f2f692e6962622e636f2f744c7a375a44442f53637265656e73686f742d66726f6d2d323032312d30352d32332d32312d31302d32392e706e67](https://user-images.githubusercontent.com/75139477/119271291-5f5c7b00-bc1a-11eb-899c-4694f7e855b8.png)

**Comment by Muhammad-Ahmad-Ali069** [comment]
onkeypress="return ((event.charCode !=8 && event.charCode ==0) || (event.charCode >= 48 && event.charCode <= 57))"

With this piece of code user will not be able to enter anything other then number in the input field of width and height 

Or you can use type=number to get only numbers from client side

**Comment by Haseb-ali** [comment]
Okay thanks
